### ISSUE TITLE
`Internal Server Error`

### ISSUE THREAD

**Issue by EzzEddin** [simonw/cougar-or-not#7]
I get this error `Internal Server Error` when I upload the image. Should I run it on a local server? Or it just works with Zeit?

**Comment by simonw** [comment]
Try running locally and you should see a more detailed error message dumped to the console.

Zeit don't support Docket deployments any more so deploying there is unlikely to work.

There's also a good chance this code no longer works with the most recent versions of the dependencies - I've not attempted to run this in over a year.
