### ISSUE TITLE
Cannot run on macOs

### ISSUE THREAD

**Issue by gerabu** [simonw/cougar-or-not#8]
Helo

I cannot get this run on macOs Catalina v10.15.2 (19C57)
i'm getting the following error

<img width="851" alt="Screen Shot 2020-03-08 at 1 09 48 PM" src="https://user-images.githubusercontent.com/7727225/76169508-8e362080-613e-11ea-8148-7f6a782f74db.png">

**Comment by mpoisot** [comment]
Fastai won't install on macos. There are some deep dependencies that fail to install. But it *will* work within Docker on a mac (Docker for Desktop). Basically you install Docker for Desktop, clone this repository, then run `docker build .`
